import { composeDocument } from '../src/lib/canon/document';
import { narrationHash, narrationSource } from '../src/lib/canon/audio';
import { narrationIssues } from '../src/lib/canon/audio-source';
const uid = process.argv[2];
if (!/^(mn|dn)[1-9]\d*$/.test(uid ?? '')) throw new Error('Provide a Majjhima or Digha UID, e.g. mn1 or dn1');
const collection = uid.startsWith('mn') ? 'mn' : 'dn';
const doc = composeDocument(collection, uid);
const source = narrationSource(doc);
const issues = narrationIssues(doc);
if (issues.length) throw new Error(`${uid}: ${issues.join('; ')}`);
console.log(JSON.stringify({ uid, title: doc.viTitle, source_sha256: narrationHash(doc), ...source }));
