import { readFileSync, writeFileSync } from 'node:fs';

const tokens = JSON.parse(readFileSync('source/design-tokens.json', 'utf8'));
const family = value => value.map(name => name.includes(' ') ? `"${name}"` : name).join(', ');
const lines = Object.entries(tokens).filter(([name]) => !name.startsWith('$')).map(([name, token]) => {
  const value = token.$value;
  let css;
  switch (token.$type) {
    case 'color':
      if (value.colorSpace !== 'srgb' || value.alpha !== 1 || value.components.length !== 3 || value.components.some(c => c < 0 || c > 1)) throw new Error(`Invalid color: ${name}`);
      css = '#' + value.components.map(c => Math.round(c * 255).toString(16).padStart(2, '0')).join('');
      break;
    case 'dimension':
    case 'duration': css = `${value.value}${value.unit}`; break;
    case 'fontFamily': css = family(value); break;
    default: throw new Error(`Unsupported token type: ${name}`);
  }
  return `  --${name}: ${css};`;
});
const output = `/* Generated by npm run design:generate. Edit source/design-tokens.json. */\n:root {\n${lines.join('\n')}\n}\n`;
const destination = 'public/styles/tokens.css';
if (process.argv.includes('--check')) {
  if (readFileSync(destination, 'utf8') !== output) throw new Error('Design tokens are stale. Run npm run design:generate.');
  console.log('Design tokens match the canonical registry.');
} else {
  writeFileSync(destination, output);
}
